name: Run Python Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .github/scripts

    steps:
      # Step 1: Check out the repository
      - name: Check out the repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests sentry-sdk

      # Step 4: Run the Python script
      - name: Run Python script
        run: |
          python sentry.py  # Replace with your actual script name
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
